/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const CoolMode: typeof import('./components/magicui/cool-mode')['CoolMode']
  const Meteors: typeof import('./components/magicui/meteors')['Meteors']
  const createRef: typeof import('react')['createRef']
  const createUserSlice: typeof import('./stores/index')['createUserSlice']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const meteors: typeof import('./components/magicui/meteors')['default']
  const startTransition: typeof import('react')['startTransition']
  const useBattery: typeof import('./hooks/useBattery')['useBattery']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useInterval: typeof import('./hooks/useInterval')['useInterval']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStore: typeof import('./stores/index')['useStore']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
